// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDgAf8yWKxg2GJDgwd_yH7DuaVJowA-K0',
    appId: '1:419833750506:web:11e9bdf338a0de47c84893',
    messagingSenderId: '419833750506',
    projectId: 'luthomoibele',
    authDomain: 'luthomoibele.firebaseapp.com',
    storageBucket: 'luthomoibele.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdWr3lZj_yLNVpiZDdZcy-Mhjh-KBfcnc',
    appId: '1:419833750506:android:dc51983af1ed5e88c84893',
    messagingSenderId: '419833750506',
    projectId: 'luthomoibele',
    storageBucket: 'luthomoibele.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6trIn_WFC4fBzhFxW7wSxNgUcpMGTMJw',
    appId: '1:419833750506:ios:b411113bcfa7767ac84893',
    messagingSenderId: '419833750506',
    projectId: 'luthomoibele',
    storageBucket: 'luthomoibele.firebasestorage.app',
    iosClientId: '419833750506-muqbmvssofq16mk89bv9r1nadf59rjef.apps.googleusercontent.com',
    iosBundleId: 'com.example.tp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB6trIn_WFC4fBzhFxW7wSxNgUcpMGTMJw',
    appId: '1:419833750506:ios:b411113bcfa7767ac84893',
    messagingSenderId: '419833750506',
    projectId: 'luthomoibele',
    storageBucket: 'luthomoibele.firebasestorage.app',
    iosClientId: '419833750506-muqbmvssofq16mk89bv9r1nadf59rjef.apps.googleusercontent.com',
    iosBundleId: 'com.example.tp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDDgAf8yWKxg2GJDgwd_yH7DuaVJowA-K0',
    appId: '1:419833750506:web:d6879811fe100047c84893',
    messagingSenderId: '419833750506',
    projectId: 'luthomoibele',
    authDomain: 'luthomoibele.firebaseapp.com',
    storageBucket: 'luthomoibele.firebasestorage.app',
  );

}